### ISSUE TITLE
ffi-napi/lib/dynamic_library.js:74 error

### ISSUE THREAD

**Issue by zhgromov** [airgram/airgram-ts-example#1]
Hi! what i should doing? i cant start example:
``` airgram-ts-example/node_modules/ffi-napi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err);
          ^
Error: Dynamic Linking Error: dlopen(/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/tdlib/libtdjson.dylib, 2): image not found
    at new DynamicLibrary (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/ffi-napi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/ffi-napi/lib/library.js:45:14)
    at new TdLib (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/airgram/src/components/TdLib.ts:37:22)
    at new TdProxy (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/airgram/src/components/TdProxy.ts:44:18)
    at new Airgram (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/airgram/src/Airgram.ts:36:20)
    at Object.<anonymous> (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/src/index.ts:6:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/evgeniygromov/IdeaProjects/tg/airgram-ts-example/node_modules/ts-node/src/index.ts:476:12)
[nodemon] app crashed - waiting for file changes before starting...
```
thanks..

**Comment by idkjs** [comment]
@zhgromov did you figure this out? If so, can you share you solution? Thank you, sir.

**Comment by sdcdsvsdv423** [comment]
You need to provide [`command`](https://airgram.io/api-reference/configuration#nodejs-version) option with the path to TDLib command:
```ts
const airgram = new Airgram({
  command: '/path/to/tdlib/libtdjson',
})
```

**Comment by sdcdsvsdv423** [comment]
Or you can open the [`.env`](https://github.com/airgram/airgram-ts-example/blob/master/.env#L3) file and fix `TDLIB_COMMAND` value.

**Comment by idkjs** [comment]
@esindger thank you, dev.
